spring:
  application:
    name: client-auth-application
  security:
    oauth2:
      client:
        registration:
          golf-client:
            provider: golf-provider
            client-id: golf-client-3732d774-4c4f-416f-b38e-580be74bc7dd
            client-secret: golf-secret-dc9abad3-c8db-4441-9060-6947b658c0a2
            authorization-grant-type: client_credentials
            scope: read
        provider:
          golf-provider:
            token-uri: http://authorization-server:9000/oauth2/token
api:
  lessons-url: "http://resource-server:8082/lessons"
