spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          # The issuer-uri configuration in Spring Boot's security OAuth2 resource server settings specifies the
          # URI of the OpenID Connect Provider (also known as the Authorization Server) that issues the JWT tokens.
          # This is a crucial configuration for JWT validation.
          issuer-uri: http://authorization-server:9000
server:
  port: 8082